### ISSUE TITLE
Cannot find module error after updating eslint to v5.0.0

### ISSUE THREAD

**Issue by bruno12mota** [relax/eslint-config-relax#2]
This is currently broken for me, after updating eslint to latest version. I think it's something to do with setting the packageName in the config file.

**Comment by magalhas** [comment]
I'm going to take a look into this ASAP.

**Comment by magalhas** [comment]
It looks like it's an issue with linter-eslint, check [here](https://github.com/AtomLinter/linter-eslint/issues/262). For the time being the best thing is to downgrade linter-eslint on Atom.

**Comment by bruno12mota** [comment]
linter-eslint 5.0.2 fixed it
